[project]
name = "whales"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "pydantic-ai>=0.0.14",
    "pydantic>=2.10.4",
    "rich>=13.9.4",
    "devtools>=0.12.2",
    "python-dotenv>=1.0.1",
]
